import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Plus } from 'lucide-react';
const DIFFICULTY_LABELS = {
    oson: 'Oson',
    orta: "O'rta",
    qiyin: 'Qiyin',
};
export default function LeftPanel({ gameState, onStartGame, onPlayAgain, onAddTests, }) {
    return (_jsxs("div", { className: "h-full flex flex-col gap-4", children: [_jsxs("button", { onClick: onAddTests, className: "w-full flex items-center justify-center gap-2 bg-gradient-primary hover:opacity-90 text-white font-bold py-3 px-4 rounded-lg transition", children: [_jsx(Plus, { size: 20 }), _jsx("span", { children: "Testlar Qo'shish" })] }), _jsxs("div", { className: "card-dark flex-1 overflow-y-auto", children: [_jsx("h2", { className: "text-xl font-bold neon-text mb-4", children: "O'yin Axbori" }), gameState.phase === 'setup' && (_jsxs("div", { className: "space-y-3", children: [_jsx("p", { className: "text-gray-400 text-sm mb-4", children: "Darajani tanlang:" }), Object.entries(DIFFICULTY_LABELS).map(([key, label]) => (_jsx("button", { onClick: () => onStartGame(key), className: "w-full py-2 px-3 bg-dark-border hover:bg-brand-primary/30 border border-brand-primary/50 rounded-lg text-white font-bold transition", children: label }, key)))] })), gameState.phase === 'running' && (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-dark-bg p-3 rounded-lg", children: [_jsx("p", { className: "text-gray-400 text-xs mb-1", children: "Qolgan Vaqt" }), _jsx("p", { className: "text-3xl font-bold neon-text", children: gameState.timeLeft }), _jsx("p", { className: "text-xs text-gray-500 mt-1", children: "soniya" })] }), _jsxs("div", { className: "bg-dark-bg p-3 rounded-lg", children: [_jsx("p", { className: "text-gray-400 text-xs mb-1", children: "Ballar" }), _jsx("p", { className: "text-3xl font-bold text-success", children: gameState.score }), _jsx("p", { className: "text-xs text-gray-500 mt-1", children: "ta to'g'ri javob" })] }), _jsxs("div", { className: "bg-dark-bg p-3 rounded-lg", children: [_jsx("p", { className: "text-gray-400 text-xs mb-2", children: "Taraqqiyot" }), _jsx("div", { className: "w-full h-2 bg-dark-border rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-gradient-primary transition-all duration-300", style: {
                                                width: `${(gameState.currentNodeIndex / 20) * 100}%`,
                                            } }) }), _jsxs("p", { className: "text-xs text-gray-500 mt-2", children: [gameState.currentNodeIndex, " / 20 svetafor"] })] }), _jsxs("div", { className: "bg-dark-bg p-3 rounded-lg", children: [_jsx("p", { className: "text-gray-400 text-xs mb-1", children: "Darajasi" }), _jsx("p", { className: "text-lg font-bold text-warning", children: gameState.selectedDifficulty
                                            ? DIFFICULTY_LABELS[gameState.selectedDifficulty]
                                            : '-' })] })] })), (gameState.phase === 'delivery' || gameState.phase === 'finished') && (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-dark-bg p-4 rounded-lg text-center", children: [_jsx("p", { className: "text-gray-400 text-xs mb-2", children: "Yakuniy Natija" }), _jsx("p", { className: `text-4xl font-bold ${gameState.phase === 'delivery'
                                            ? 'text-success'
                                            : 'text-error'}`, children: gameState.score })] }), gameState.bonus > 0 && (_jsxs("div", { className: "bg-green-900/30 border border-success p-4 rounded-lg text-center", children: [_jsx("p", { className: "text-gray-300 text-xs mb-2", children: "Bonus" }), _jsxs("p", { className: "text-2xl font-bold text-success", children: ["+", gameState.bonus.toLocaleString('uz-UZ')] })] })), _jsx("button", { onClick: onPlayAgain, className: "w-full py-2 px-3 bg-brand-primary hover:opacity-90 text-white font-bold rounded-lg transition", children: "Yana o'yna" })] }))] })] }));
}
