"""Add explanation and difficulty to game tests

Revision ID: 5595e5988419
Revises: 
Create Date: 2026-03-11 10:13:43.406364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5595e5988419'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_test_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_test_sets_game_key'), 'game_test_sets', ['game_key'], unique=False)
    op.create_index(op.f('ix_game_test_sets_id'), 'game_test_sets', ['id'], unique=False)
    op.create_index('ix_game_test_sets_teacher_game', 'game_test_sets', ['teacher_id', 'game_key'], unique=False)
    op.create_index(op.f('ix_game_test_sets_teacher_id'), 'game_test_sets', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_game_test_sets_title'), 'game_test_sets', ['title'], unique=False)
    op.create_table('game_test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_set_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('qhash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['test_set_id'], ['game_test_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_test_questions_id'), 'game_test_questions', ['id'], unique=False)
    op.create_index(op.f('ix_game_test_questions_qhash'), 'game_test_questions', ['qhash'], unique=True)
    op.create_index(op.f('ix_game_test_questions_test_set_id'), 'game_test_questions', ['test_set_id'], unique=False)
    op.create_table('game_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['game_test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_options_id'), 'game_options', ['id'], unique=False)
    op.create_index(op.f('ix_game_options_question_id'), 'game_options', ['question_id'], unique=False)
    op.drop_index('ix_game_progress_game_name', table_name='game_progress')
    op.drop_index('ix_game_progress_id', table_name='game_progress')
    op.drop_index('ix_game_progress_user_id', table_name='game_progress')
    op.drop_table('game_progress')
    op.drop_index('ix_subjects_id', table_name='subjects')
    op.drop_index('ix_subjects_name', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_options_id', table_name='options')
    op.drop_table('options')
    op.drop_index('ix_rooster_questions_id', table_name='rooster_questions')
    op.drop_index('ix_rooster_questions_number', table_name='rooster_questions')
    op.drop_table('rooster_questions')
    op.drop_index('ix_sections_id', table_name='sections')
    op.drop_index('ix_sections_subject_id', table_name='sections')
    op.drop_index('ix_sections_teacher_name', table_name='sections')
    op.drop_index('ix_sections_title', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_tests_id', table_name='tests')
    op.drop_index('ix_tests_title', table_name='tests')
    op.drop_table('tests')
    op.drop_index('ix_team_game_progress_game_name', table_name='team_game_progress')
    op.drop_index('ix_team_game_progress_id', table_name='team_game_progress')
    op.drop_index('ix_team_game_progress_section_number', table_name='team_game_progress')
    op.drop_table('team_game_progress')
    op.drop_index('ix_game_questions_game_name', table_name='game_questions')
    op.drop_index('ix_game_questions_id', table_name='game_questions')
    op.drop_index('ix_game_questions_section_number', table_name='game_questions')
    op.drop_table('game_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_name', sa.VARCHAR(), nullable=True),
    sa.Column('question_text', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correct_answer', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('section_number', sa.INTEGER(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.Column('formula', sa.TEXT(), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_questions_section_number', 'game_questions', ['section_number'], unique=False)
    op.create_index('ix_game_questions_id', 'game_questions', ['id'], unique=False)
    op.create_index('ix_game_questions_game_name', 'game_questions', ['game_name'], unique=False)
    op.create_table('team_game_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_name', sa.VARCHAR(), nullable=True),
    sa.Column('section_number', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('team1_player_id', sa.INTEGER(), nullable=True),
    sa.Column('team2_player_id', sa.INTEGER(), nullable=True),
    sa.Column('team1_score', sa.INTEGER(), nullable=True),
    sa.Column('team2_score', sa.INTEGER(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('winner', sa.VARCHAR(), nullable=True),
    sa.Column('total_time_spent', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_game_progress_section_number', 'team_game_progress', ['section_number'], unique=False)
    op.create_index('ix_team_game_progress_id', 'team_game_progress', ['id'], unique=False)
    op.create_index('ix_team_game_progress_game_name', 'team_game_progress', ['game_name'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('teacher_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tests_title', 'tests', ['title'], unique=False)
    op.create_index('ix_tests_id', 'tests', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('teacher_name', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sections_title', 'sections', ['title'], unique=False)
    op.create_index('ix_sections_teacher_name', 'sections', ['teacher_name'], unique=False)
    op.create_index('ix_sections_subject_id', 'sections', ['subject_id'], unique=False)
    op.create_index('ix_sections_id', 'sections', ['id'], unique=False)
    op.create_table('rooster_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('question', sa.VARCHAR(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correctAnswer', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rooster_questions_number', 'rooster_questions', ['number'], unique=False)
    op.create_index('ix_rooster_questions_id', 'rooster_questions', ['id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_options_id', 'options', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('test_id', sa.INTEGER(), nullable=True),
    sa.Column('correct_option', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subjects_name', 'subjects', ['name'], unique=False)
    op.create_index('ix_subjects_id', 'subjects', ['id'], unique=False)
    op.create_table('game_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('game_name', sa.VARCHAR(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('section_number', sa.INTEGER(), nullable=True),
    sa.Column('time_spent', sa.FLOAT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_progress_user_id', 'game_progress', ['user_id'], unique=False)
    op.create_index('ix_game_progress_id', 'game_progress', ['id'], unique=False)
    op.create_index('ix_game_progress_game_name', 'game_progress', ['game_name'], unique=False)
    op.drop_index(op.f('ix_game_options_question_id'), table_name='game_options')
    op.drop_index(op.f('ix_game_options_id'), table_name='game_options')
    op.drop_table('game_options')
    op.drop_index(op.f('ix_game_test_questions_test_set_id'), table_name='game_test_questions')
    op.drop_index(op.f('ix_game_test_questions_qhash'), table_name='game_test_questions')
    op.drop_index(op.f('ix_game_test_questions_id'), table_name='game_test_questions')
    op.drop_table('game_test_questions')
    op.drop_index(op.f('ix_game_test_sets_title'), table_name='game_test_sets')
    op.drop_index(op.f('ix_game_test_sets_teacher_id'), table_name='game_test_sets')
    op.drop_index('ix_game_test_sets_teacher_game', table_name='game_test_sets')
    op.drop_index(op.f('ix_game_test_sets_id'), table_name='game_test_sets')
    op.drop_index(op.f('ix_game_test_sets_game_key'), table_name='game_test_sets')
    op.drop_table('game_test_sets')
    # ### end Alembic commands ###
